[toolchain]
anchor_version = "0.28.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
custom_dao_program = "8gQrxcan9ehYJEaw8tG1dZYJNwoNoh6QxQ9MzmWESR11"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[test]
startup_wait = 10000
validator = { url = "tcp://127.0.0.1:8899" }

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
