[toolchain]
anchor_version = "0.24.2"

[features]
seeds = false
skip-lint = false

[programs.devnet]
custom_dao = "FpSSbLNqGCcEwdBdk34Gs8b722LTAvNGCET6xNr55oLC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
types = "target/types"
members = [
    "programs/custom-dao"
]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
