[workspace]
members = [
    "programs/custom-dao"
]
resolver = "2"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
opt-level = 3
panic = "abort"
strip = true
debug = false
incremental = false
